apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: issho
  labels: &labels
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: issho-ni
    app.kubernetes.io/name: mongodb
spec:
  selector:
    <<: *labels
  clusterIP: None
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
