apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: issho
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: issho-ni
    app.kubernetes.io/name: mongodb
spec:
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: issho-ni
    app.kubernetes.io/name: mongodb
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
