apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: issho
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: issho-ni
    app.kubernetes.io/name: mongodb
spec:
  serviceName: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: issho-ni
        app.kubernetes.io/name: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage-claim
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage-claim
        annotations:
          volume.beta.kubernetes.io/storage-class: "hostpath"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
