apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  namespace: issho
  labels: &labels
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: issho-ni
    app.kubernetes.io/name: graphql
spec:
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      containers:
        - name: graphql
          image: docker.io/issho/graphql
          resources:
            limits:
              memory: 64Mi
              cpu: 100m
          env:
            - name: GRAPHQL_PORT
              value: "8080"
            - name: KAZOKU_URL
              value: kazoku.issho.svc:443
            - name: NINKA_URL
              value: ninka.issho.svc:443
            - name: NINSHOU_URL
              value: ninshou.issho.svc:443
            - name: SHINNINJOU_URL
              value: shinninjou.issho.svc:443
            - name: YOUJI_URL
              value: youji.issho.svc:443
            - name: TLS_CERT
              value: /cert.pem
            - name: TLS_KEY
              value: /key.pem
          ports:
            - name: https
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /live
              scheme: HTTPS
              port: https
          readinessProbe:
            httpGet:
              path: /ready
              scheme: HTTPS
              port: https
