apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  namespace: issho
spec:
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql
          image: gcr.io/issho-ni/issho-graphql
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: GRAPHQL_PORT
              value: "8080"
            - name: NINSHOU_URL
              value: ninshou.issho.svc.cluster.local:443
            - name: YOUJI_URL
              value: youji.issho.svc.cluster.local:443
          ports:
            - name: https
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /live
              scheme: HTTPS
              port: https
          readinessProbe:
            httpGet:
              path: /ready
              scheme: HTTPS
              port: https
