apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  namespace: issho
  labels:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: issho-ni
    app.kubernetes.io/name: graphql
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: issho-ni
      app.kubernetes.io/name: graphql
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: issho-ni
        app.kubernetes.io/name: graphql
    spec:
      containers:
        - name: graphql
          image: gcr.io/issho-ni/graphql
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: GRAPHQL_PORT
              value: "8080"
            - name: KAZOKU_URL
              value: kazoku:443
            - name: NINKA_URL
              value: ninka:443
            - name: NINSHOU_URL
              value: ninshou:443
            - name: SHINNINJOU_URL
              value: shinninjou:443
            - name: YOUJI_URL
              value: youji:443
          ports:
            - name: https
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /live
              scheme: HTTPS
              port: https
          readinessProbe:
            httpGet:
              path: /ready
              scheme: HTTPS
              port: https
