apiVersion: v1
kind: Service
metadata:
  name: graphql
  namespace: issho
  labels: &labels
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: issho-ni
    app.kubernetes.io/name: graphql
spec:
  selector:
    <<: *labels
  ports:
    - name: https
      port: 443
      targetPort: https
