resources:
  containers:
    - container: buildkit
      image: jbhannah/buildkit-ubuntu:latest
      options: --privileged -v "/usr/bin/docker":"/usr/bin/docker"
jobs:
  - job: builder
    dependsOn: []
    pool:
      vmImage: ubuntu-latest
    container: buildkit
    steps:
      - task: CacheBeta@0
        inputs:
          key: ./Dockerfile | ./go.sum | "builder"
          path: ./cache/builder
      - script: |
          sudo ci/scripts/build.sh builder
  - job: installer
    dependsOn:
      - builder
    pool:
      vmImage: ubuntu-latest
    container: buildkit
    steps:
      - task: CacheBeta@0
        inputs:
          key: ./Dockerfile | ./go.sum | "builder"
          path: ./cache/builder
      - task: CacheBeta@0
        inputs:
          key: '**/*.go | "installer"'
          path: ./cache/installer
      - script: |
          sudo ci/scripts/build.sh installer
  - job: base
    dependsOn: []
    pool:
      vmImage: ubuntu-latest
    container: buildkit
    steps:
      - task: CacheBeta@0
        inputs:
          key: ./Dockerfile | "base"
          path: ./cache/base
      - script: |
          sudo ci/scripts/build.sh base
  - job: images
    dependsOn:
      - base
      - installer
    pool:
      vmImage: ubuntu-latest
    container: buildkit
    strategy:
      matrix:
        graphql:
          command: graphql
        kazoku:
          command: kazoku
        ninka:
          command: ninka
        ninshou:
          command: ninshou
        shinninjou:
          command: shinninjou
        youji:
          command: youji
    steps:
      - task: CacheBeta@0
        inputs:
          key: '**/*.go | "installer"'
          path: ./cache/installer
      - task: CacheBeta@0
        inputs:
          key: ./Dockerfile | "base"
          path: ./cache/base
      - script: |
          sudo ci/script/build.sh | docker load
        env:
          BUILDCTL_ARGS: --opt build-arg:COMMAND=$(command) --output type=docker,name=issho/$(command)
      - task: Docker@2
        inputs:
          command: push
          repository: issho/$(command)
