apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
    - image: gcr.io/issho-ni/issho-graphql
      docker:
        buildArgs:
          CERT_HOST: "*.issho.svc.cluster.local"
          COMMAND: graphql
    - image: gcr.io/issho-ni/issho-ninshou
      docker:
        buildArgs:
          CERT_HOST: "*.issho.svc.cluster.local"
          COMMAND: ninshou
    - image: gcr.io/issho-ni/issho-youji
      docker:
        buildArgs:
          CERT_HOST: "*.issho.svc.cluster.local"
          COMMAND: youji
deploy:
  kustomize:
    path: deployments/k8s
