apiVersion: apps/v1
kind: Deployment
metadata:
  name: ninka
  namespace: issho
  labels:
    app.kubernetes.io/component: authorization
    app.kubernetes.io/instance: issho-ni
    app.kubernetes.io/name: ninka
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: authorization
      app.kubernetes.io/instance: issho-ni
      app.kubernetes.io/name: ninka
  template:
    metadata:
      labels:
        app.kubernetes.io/component: authorization
        app.kubernetes.io/instance: issho-ni
        app.kubernetes.io/name: ninka
    spec:
      containers:
        - name: ninka
          image: gcr.io/issho-ni/ninka
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          env:
            - name: NINKA_PORT
              value: "8084"
            - name: MONGODB_URL
              value: mongodb://mongodb:27017
          ports:
            - name: https
              containerPort: 8084
