apiVersion: v1
kind: Secret
metadata:
  name: ninka
  namespace: issho
  labels:
    app.kubernetes.io/component: authorization
    app.kubernetes.io/instance: issho-ni
    app.kubernetes.io/name: ninka
data:
  NINKA_JWT_SECRET: K1gzUmUvWnlya2t3QXd1bWhFWXpyY1pDenlha2g5blhTSWJzUGJjWFpSaU5ZY25nVkJ5akg3ODVodGFGbm5BR0ZWa1B0M3o1Yml2Zm4raXl1c3R3a2J4dHhiY0ZYVzlEYlFJWElOTW5Vdmc2VXo2RnYweTZIYWx5MW1lVG5PUS83WU9pS3IxTW00UExBQ09GMDdYbEVrNTlMNURCcXpsNVAxUkJIZ3ZOdGpVPQ==
