apiVersion: v1
kind: Service
metadata:
  name: ninka
  namespace: issho
  labels: &labels
    app.kubernetes.io/component: authorization
    app.kubernetes.io/instance: issho-ni
    app.kubernetes.io/name: ninka
spec:
  selector:
    <<: *labels
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: https
