---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: issho/concourse-buildkit

params:
  CACHE_MODE: max
  CACHE_REGISTRY_REF: docker.io/issho/issho-build-cache
  CONTEXT: git
  REPOSITORY: gcr.io/issho-ni/((target))
  TARGET: ((target))

inputs:
  - name: git
  - name: cache-input
    optional: true

outputs:
  - name: image

run:
  path: git/ci/scripts/build.sh
