---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: issho/concourse-buildkit

params:
  CACHE_INPUT_DIR: cache-input
  CACHE_MODE: max
  CONTEXT: git
  REPOSITORY: issho/concourse-buildkit

inputs:
  - name: git
  - name: cache-input
    optional: true

outputs:
  - name: image
  - name: cache

caches:
  - path: cache

run:
  path: build
