---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: issho/concourse-buildkit

params:
  CACHE_MODE: max
  CACHE_REGISTRY_REF: docker.io/issho/issho-build-cache
  CONTEXT: git
  DOCKER_HUB_USERNAME: ((docker-hub.username))
  DOCKER_HUB_PASSWORD: ((docker-hub.password))

inputs:
  - name: git

outputs:
  - name: image

run:
  path: git/ci/scripts/build.sh
