---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: issho/concourse-buildkit

params:
  CACHE_MODE: max
  CACHE_REGISTRY_REF: gcr.io/issho-ni/cache
  CONTEXT: git
  GCR_JSON_KEY: ((iam.ops-concourse-json))

inputs:
  - name: git

outputs:
  - name: image

run:
  path: git/ci/scripts/build.sh
