---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: issho/concourse-buildkit

params:
  CACHE_EXPORT_MODE: max
  CACHE_EXPORT_TYPE: none
  CACHE_IMPORT_REF: docker.io/issho/issho-build-cache
  CONTEXT: git
  REPOSITORY: gcr.io/issho-ni/((target))
  TARGET: ((target))

inputs:
  - name: git
  - name: cache
    optional: true

outputs:
  - name: image
  - name: cache

run:
  path: git/ci/scripts/build.sh
