---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ananace/skopeo

inputs:
  - name: git
  - name: cache

outputs:
  - name: cache

run:
  path: git/ci/scripts/cache.sh
