---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: gcr.io/issho-ni/builder
    username: _json_key
    password: ((iam.ops-concourse-json))

params:
  CODECOV_TOKEN: ((codecov.token))

inputs:
  - name: git

run:
  dir: git
  path: ci/scripts/coverage.sh
