---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: gcr.io/issho-ni/builder
    username: _json_key
    password: ((default-token.token))
inputs:
  - name: issho-git
run:
  dir: issho-git
  path: scripts/issho-tests.sh
