---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: gcr.io/issho-ni/builder
    username: _json_key
    password: ((iam.ops-concourse-json))
inputs:
  - name: git
run:
  dir: git
  path: ci/scripts/tests.sh
