apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ninshou.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ninshou.name" . }}
    helm.sh/chart: {{ include "ninshou.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ninshou.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ninshou.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: {{ .Values.deployment.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: https
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: https
          env:
            - name: NINSHOU_PORT
              value: "{{ .Values.deployment.port }}"
            - name: MONGODB_USER
              value: root
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: issho-mongodb
                  key: mongodb-root-password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
