apiVersion: apps/v1
kind: Deployment
metadata:
  name: youji
  namespace: issho
  labels: &labels
    app.kubernetes.io/component: tasks
    app.kubernetes.io/instance: issho-ni
    app.kubernetes.io/name: youji
spec:
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      containers:
        - name: youji
          image: docker.io/issho/youji
          resources:
            limits:
              memory: 64Mi
              cpu: 100m
          env:
            - name: YOUJI_PORT
              value: "8083"
            - name: MONGODB_URL
              value: mongodb://mongodb:27017
          ports:
            - name: https
              containerPort: 8083
