apiVersion: v1
kind: Service
metadata:
  name: youji
  namespace: issho
  labels:
    app.kubernetes.io/component: tasks
    app.kubernetes.io/instance: issho-ni
    app.kubernetes.io/name: youji
spec:
  selector:
    app.kubernetes.io/component: tasks
    app.kubernetes.io/instance: issho-ni
    app.kubernetes.io/name: youji
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: https
