apiVersion: apps/v1
kind: Deployment
metadata:
  name: ninshou
  namespace: issho
  labels: &labels
    app.kubernetes.io/component: users
    app.kubernetes.io/instance: issho-ni
    app.kubernetes.io/name: ninshou
spec:
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      containers:
        - name: ninshou
          image: docker.io/issho/ninshou
          resources:
            limits:
              memory: 64Mi
              cpu: 100m
          env:
            - name: NINSHOU_PORT
              value: "8081"
            - name: MONGODB_URL
              value: mongodb://mongodb:27017
            - name: TLS_CERT
              value: /cert.pem
            - name: TLS_KEY
              value: /key.pem
          ports:
            - name: https
              containerPort: 8081
