// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/issho-ni/issho/api/kazoku"
	"github.com/issho-ni/issho/api/ninshou"
)

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token   string          `json:"token"`
	Account *kazoku.Account `json:"account"`
	User    *ninshou.User   `json:"user"`
}

type NewAccount struct {
	Name string   `json:"name"`
	User *NewUser `json:"user"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
