// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/issho-ni/issho/api/ninshou"
)

type LoginResponse struct {
	Token string       `json:"token"`
	User  ninshou.User `json:"user"`
}
