---
resource_types:
  - name: concourse-pipeline
    type: registry-image
    source:
      repository: concourse/concourse-pipeline-resource

resources:
  - name: issho-git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/issho-ni/issho.git
  - name: issho-pipeline
    type: concourse-pipeline
    icon: fan
    source:
      teams:
        - name: main
          username: ((concourse.username))
          password: ((concourse.password))
  - name: golang-base-image
    type: registry-image
    icon: docker
    source:
      repository: golang
      tag: 1.12-alpine
  - name: issho-builder-image
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/builder
      username: _json_key
      password: ((default-token.token))

jobs:
  - name: pipeline
    plan:
      - get: issho-git
        trigger: true
      - put: issho-pipeline
        params:
          pipelines:
            - name: issho
              team: main
              config_file: issho-git/ci/pipeline.yml
  - name: builder
    plan:
      - in_parallel:
          - get: issho-git
            trigger: true
          - get: issho-pipeline
            trigger: true
          - get: golang-base-image
            trigger: true
      - task: issho-builder
        file: issho-git/ci/tasks/issho-builder.yml
        privileged: true
      - put: issho-builder-image
        params:
          image: issho-builder-image/image.tar
  - name: tests
    plan:
      - in_parallel:
          - get: issho-git
            passed:
              - builder
          - get: issho-builder-image
            trigger: true
            passed:
              - builder
      - task: issho-tests
        image: issho-builder-image
        file: issho-git/ci/tasks/issho-tests.yml
