---
resource_types:
  - name: concourse-pipeline
    type: docker-image
    source:
      repository: concourse/concourse-pipeline-resource

resources:
  - name: issho-git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/issho-ni/issho.git
  - name: issho-pipeline
    type: concourse-pipeline
    icon: fan
    source:
      teams:
        - name: main
          username: ((concourse.username))
          password: ((concourse.password))
  - name: golang-base-docker
    type: docker-image
    icon: docker
    source:
      repository: golang
      tag: 1.12-alpine
  - name: issho-builder-docker
    type: docker-image
    icon: docker
    source:
      repository: issho/builder
      username: ((docker-hub.username))
      password: ((docker-hub.password))

jobs:
  - name: pipeline
    plan:
      - get: issho-git
        trigger: true
      - put: issho-pipeline
        params:
          pipelines:
            - name: issho
              team: main
              config_file: issho-git/ci/pipeline.yml
  - name: builder
    plan:
      - in_parallel:
          - get: issho-git
            trigger: true
          - get: issho-pipeline
            trigger: true
          - get: golang-base-docker
            trigger: true
            params:
              save: true
      - put: issho-builder-docker
        params:
          build: issho-git
          cache: true
          load_base: golang-base-docker
          save: true
          target_name: builder
  - name: tests
    plan:
      - in_parallel:
          - get: issho-git
            passed:
              - builder
          - get: issho-builder-docker
            trigger: true
            passed:
              - builder
      - task: issho-tests
        image: issho-builder-docker
        file: issho-git/ci/tasks/issho-tests.yml
