---
resource_types:
  - name: concourse-pipeline
    type: registry-image
    source:
      repository: concourse/concourse-pipeline-resource

resources:
  - name: issho-git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/issho-ni/issho.git
      ignore_paths:
        - ci/
        - deployments/
        - scripts/
  - name: issho-pipeline-git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/issho-ni/issho.git
      paths:
        - ci/
        - deployments/
        - scripts/
  - name: issho-pipeline
    type: concourse-pipeline
    icon: fan
    source:
      teams:
        - name: main
          username: ((concourse.username))
          password: ((concourse.password))
  - name: golang-base-image
    type: docker-image
    icon: docker
    source:
      repository: golang
      tag: 1.12-alpine
  - name: issho-builder-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/builder
      username: _json_key
      password: ((iam.ops-concourse-json))
  - name: issho-install-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/install
      username: _json_key
      password: ((iam.ops-concourse-json))
  - name: issho-certs-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/certs
      username: _json_key
      password: ((iam.ops-concourse-json))
  - name: issho-scratch-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/scratch
      username: _json_key
      password: ((iam.ops-concourse-json))
  - name: issho-graphql-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/graphql
      username: _json_key
      password: ((iam.ops-concourse-json))
  - name: issho-ninka-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/ninka
      username: _json_key
      password: ((iam.ops-concourse-json))
  - name: issho-ninshou-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/ninshou
      username: _json_key
      password: ((iam.ops-concourse-json))
  - name: issho-shinninjou-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/shinninjou
      username: _json_key
      password: ((iam.ops-concourse-json))
  - name: issho-youji-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/youji
      username: _json_key
      password: ((iam.ops-concourse-json))

groups:
  - name: issho
    jobs:
      - builder
      - tests
      - images
  - name: pipeline
    jobs:
      - pipeline

jobs:
  - name: pipeline
    plan:
      - get: issho-pipeline-git
        trigger: true
      - put: issho-pipeline
        params:
          pipelines:
            - name: issho
              team: main
              config_file: issho-pipeline-git/ci/pipeline.yml
  - name: builder
    plan:
      - in_parallel:
          - get: issho-git
            trigger: true
          - get: golang-base-image
            trigger: true
            params:
              save: true
      - put: issho-builder-image
        params:
          build: issho-git
          cache: true
          load_bases:
            - golang-base-image
          tag_file: issho-git/.git/short_ref
          target_name: builder
  - name: tests
    plan:
      - in_parallel:
          - get: issho-git
            trigger: true
            passed:
              - builder
          - get: issho-builder-image
            trigger: true
            passed:
              - builder
            params:
              save: true
      - task: issho-tests
        image: issho-builder-image
        file: issho-git/ci/tasks/issho-tests.yml
  - name: images
    plan:
      - in_parallel:
          - get: issho-git
            trigger: true
            passed:
              - tests
          - get: issho-builder-image
            trigger: true
            passed:
              - tests
            params:
              save: true
      - put: issho-install-image
        params:
          build: issho-git
          cache: true
          cache_from:
            - issho-builder-image
          tag_file: issho-git/.git/short_ref
          target_name: install
        get_params:
          save: true
      - put: issho-certs-image
        params:
          build: issho-git
          cache: true
          target_name: certs
        get_params:
          save: true
      - put: issho-scratch-image
        params:
          build: issho-git
          cache: true
          cache_from:
            - issho-certs-image
          target_name: scratch-base
        get_params:
          save: true
      - in_parallel:
          - put: issho-graphql-image
            params:
              build: issho-git
              build_args:
                COMMAND: graphql
              cache: true
              cache_from:
                - issho-install-image
              load_bases:
                - issho-scratch-image
              tag_file: issho-git/.git/short_ref
          - put: issho-ninka-image
            params:
              build: issho-git
              build_args:
                COMMAND: ninka
              cache: true
              cache_from:
                - issho-install-image
              load_bases:
                - issho-scratch-image
              tag_file: issho-git/.git/short_ref
          - put: issho-ninshou-image
            params:
              build: issho-git
              build_args:
                COMMAND: ninshou
              cache: true
              cache_from:
                - issho-install-image
              load_bases:
                - issho-scratch-image
              tag_file: issho-git/.git/short_ref
          - put: issho-shinninjou-image
            params:
              build: issho-git
              build_args:
                COMMAND: shinninjou
              cache: true
              cache_from:
                - issho-install-image
              load_bases:
                - issho-scratch-image
              tag_file: issho-git/.git/short_ref
          - put: issho-youji-image
            params:
              build: issho-git
              build_args:
                COMMAND: youji
              cache: true
              cache_from:
                - issho-install-image
              load_bases:
                - issho-scratch-image
              tag_file: issho-git/.git/short_ref
