---
resource_types:
  - name: concourse-pipeline
    type: registry-image
    source:
      repository: concourse/concourse-pipeline-resource

resources:
  - name: git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/issho-ni/issho.git
      ignore_paths:
        - ci/pipeline.yml
        - deployments/
  - name: pipeline-git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/issho-ni/issho.git
      paths:
        - ci/pipeline.yml
  - name: pipeline
    type: concourse-pipeline
    icon: fan
    source:
      teams:
        - name: main
          username: ((concourse.username))
          password: ((concourse.password))
  - name: golang
    type: registry-image
    icon: docker
    source:
      repository: golang
      tag: 1.12-alpine
  - name: builder
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/builder
      username: _json_key
      password: ((iam.ops-concourse-json))
  - name: graphql
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/graphql
      username: _json_key
      password: ((iam.ops-concourse-json))
  - name: ninka
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/ninka
      username: _json_key
      password: ((iam.ops-concourse-json))
  - name: ninshou
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/ninshou
      username: _json_key
      password: ((iam.ops-concourse-json))
  - name: shinninjou
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/shinninjou
      username: _json_key
      password: ((iam.ops-concourse-json))
  - name: youji
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/issho-ni/youji
      username: _json_key
      password: ((iam.ops-concourse-json))

groups:
  - name: issho
    jobs:
      - builder
      - tests
      - images
  - name: pipeline
    jobs:
      - pipeline

jobs:
  - name: pipeline
    plan:
      - get: pipeline-git
        trigger: true
      - put: pipeline
        params:
          pipelines:
            - name: issho
              team: main
              config_file: pipeline-git/ci/pipeline.yml
  - name: builder
    plan:
      - in_parallel:
          - get: git
            trigger: true
          - get: golang
            trigger: true
      - task: builder
        file: git/ci/tasks/builder.yml
        privileged: true
        params:
          DOCKER_HUB_USERNAME: ((docker-hub.username))
          DOCKER_HUB_PASSWORD: ((docker-hub.password))
          REPOSITORY: gcr.io/issho-ni/builder
      - in_parallel:
          - put: builder
            params:
              image: image/image.tar
              additional_tags: git/.git/short_ref
  - name: tests
    plan:
      - in_parallel:
          - get: git
            trigger: true
            passed:
              - builder
          - get: builder
            trigger: true
            passed:
              - builder
      - task: tests
        image: builder
        file: git/ci/tasks/tests.yml
  - name: images
    plan:
      - in_parallel:
          - get: git
            trigger: true
            passed:
              - tests
          - get: builder
            trigger: true
            passed:
              - tests
      - task: cache
        file: git/ci/tasks/cache.yml
        privileged: true
        output_mapping:
          cache: cache-input
      - in_parallel:
          - task: graphql
            file: git/ci/tasks/builder.yml
            privileged: true
            params:
              CACHE_INPUT_DIR: cache-input
              TARGET: graphql
              REPOSITORY: gcr.io/issho-ni/graphql
            output_mapping:
              image: graphql
          - task: ninka
            file: git/ci/tasks/builder.yml
            privileged: true
            params:
              CACHE_INPUT_DIR: cache-input
              TARGET: ninka
              REPOSITORY: gcr.io/issho-ni/ninka
            output_mapping:
              image: ninka
          - task: ninshou
            file: git/ci/tasks/builder.yml
            privileged: true
            params:
              CACHE_INPUT_DIR: cache-input
              TARGET: ninshou
              REPOSITORY: gcr.io/issho-ni/ninshou
            output_mapping:
              image: ninshou
          - task: shinninjou
            file: git/ci/tasks/builder.yml
            privileged: true
            params:
              CACHE_INPUT_DIR: cache-input
              TARGET: shinninjou
              REPOSITORY: gcr.io/issho-ni/shinninjou
            output_mapping:
              image: shinninjou
          - task: youji
            file: git/ci/tasks/builder.yml
            privileged: true
            params:
              CACHE_INPUT_DIR: cache-input
              TARGET: youji
              REPOSITORY: gcr.io/issho-ni/youji
            output_mapping:
              image: youji
      - in_parallel:
          - put: graphql
            params:
              image: graphql/image.tar
              additional_tags: git/.git/short_ref
          - put: ninka
            params:
              image: ninka/image.tar
              additional_tags: git/.git/short_ref
          - put: ninshou
            params:
              image: ninshou/image.tar
              additional_tags: git/.git/short_ref
          - put: shinninjou
            params:
              image: shinninjou/image.tar
              additional_tags: git/.git/short_ref
          - put: youji
            params:
              image: youji/image.tar
              additional_tags: git/.git/short_ref
